# 1. Get all links from districts
PREFIX default: <http://smartcity.linkeddata.es/lcc/ontology/MadridEvents#>
  SELECT DISTINCT ?x ?link WHERE { 
    ?x a default:District.
    ?x owl:sameAs ?link
    
   
  } 
  

# 2. Get all links for Neighbourhood
PREFIX default: <http://smartcity.linkeddata.es/lcc/ontology/MadridEvents#>
  SELECT DISTINCT ?x ?link WHERE { 
    ?x a default:Neighbourhood.
    ?x owl:sameAs ?link
    

  } 
  
# 3. Get all links for Days of Week
PREFIX default: <http://smartcity.linkeddata.es/lcc/ontology/MadridEvents#>
  SELECT DISTINCT ?x ?link WHERE { 
    ?x a default:DayOfWeek.
    ?x owl:sameAs ?link
    
   
  } 
