
# 1. Get all facilities with accessibility
PREFIX default: <http://smartcity.linkeddata.es/lcc/ontology/MadridEvents#>
  SELECT ?x WHERE { 
    ?x a default:Facility. 
    ?x default:accessible "true"^^xsd:boolean
  }
  

# 2. Get for all long-events the id and the days of week
PREFIX default: <http://smartcity.linkeddata.es/lcc/ontology/MadridEvents#>
  SELECT ?x ?y WHERE { 
    ?x a default:Event. 
    ?x default:longEvent "true"^^xsd:boolean.
    ?x default:dayOfWeek ?y
  }
  
  
# 3. Get all Neighbourhood in which there is an event
PREFIX default: <http://smartcity.linkeddata.es/lcc/ontology/MadridEvents#>
  SELECT ?x WHERE { 
    ?x a default:Neighbourhood
  
  } 

# 4. Get ids of the category ActividadesCalleArteUrbano
PREFIX default: <http://smartcity.linkeddata.es/lcc/ontology/MadridEvents#>
  SELECT ?x WHERE { 
    ?x a default:Event.
    ?x default:isA <http://smartcity.linkeddata.es/lcc/resource/MadridEvents/ActividadesCalleArteUrbano>

  } 
# 5. Get the address of the events and their latitude and longitude
PREFIX default: <http://smartcity.linkeddata.es/lcc/ontology/MadridEvents#>
  SELECT ?s  ?lat ?long WHERE { 
    ?x a default:Event.
    ?x default:takesPlaceIn ?y.
    ?y default:hasAddress ?s.
    ?s default:hasCoordinates ?c.
    ?c default:latitude ?lat.
    ?c default:longitude ?long. 
    

  } 
