# 1.- All existing streets with their label and the district they belong to

PREFIX ont: <http://www.group02.org/pd/ontology/PedestriansMadrid#>
SELECT ?street ?streetName ?district WHERE {
  ?street rdf:type ont:Street.
  ?street rdfs:label ?streetName.
  ?street ont:hasDistrict ?district
}

# 2.- All existing districts

PREFIX ont: <http://www.group02.org/pd/ontology/PedestriansMadrid#>
SELECT ?district ?districtName WHERE {
  ?district rdf:type ont:District.
  ?district rdfs:label ?districtName
}

# 3.- All existing measurement points and their information

PREFIX ont: <http://www.group02.org/pd/ontology/PedestriansMadrid#>
SELECT ?measurement_point ?id ?street ?number ?postCode ?obs ?latitude ?longitude WHERE {
  ?measurement_point rdf:type ont:MeasurementPoint.
  ?measurement_point ont:id ?id.
  ?measurement_point ont:hasStreet ?street.
  ?measurement_point ont:hasNumber ?number.
  ?measurement_point ont:hasPostCode ?postCode.
  ?measurement_point ont:hasObservation ?obs.
  ?measurement_point ont:hasLatitude ?latitude.
  ?measurement_point ont:hasLongitude ?longitude
}

# 4.- All measurement points and the amount of measurements associated to each one

PREFIX ont: <http://www.group02.org/pd/ontology/PedestriansMadrid#>
SELECT ?measurement_point (COUNT(?measurement) AS ?nMeasurements) WHERE  {
  ?measurement_point rdf:type ont:MeasurementPoint.
  ?measurement ont:isLocated ?measurement_point.
} GROUP BY ?measurement_point

# 5.- Minimum and maximum number of pedestrians for a single measurement

PREFIX ont: <http://www.group02.org/pd/ontology/PedestriansMadrid#>
SELECT (MAX(?pedestrians) AS ?max) (MIN(?pedestrians) AS ?min) WHERE  {
  ?measurement ont:hasPedestrians ?pedestrians.
}

# 6.- Number of days that have at least one measurement

PREFIX ont: <http://www.group02.org/pd/ontology/PedestriansMadrid#>
SELECT (COUNT(distinct day(?date)) AS ?ndays) WHERE  {
  ?measurement rdf:type ont:Measurement.
  ?measurement ont:hasDate ?date
}

# 7.- Amount of measurements

PREFIX ont: <http://www.group02.org/pd/ontology/PedestriansMadrid#>
SELECT (COUNT(*) AS ?nMeasurements) WHERE  {
  ?measurement rdf:type ont:Measurement.
}

# 8.- All districts and the amount of measurements associated to each one

PREFIX ont: <http://www.group02.org/pd/ontology/PedestriansMadrid#>
SELECT ?district (COUNT(*) AS ?nMeasurements) WHERE  {
  ?measurement ont:isLocated ?measurement_point.
  ?measurement_point ont:hasStreet ?street.
  ?street ont:hasDistrict ?district.
  ?district rdf:type ont:District.
} GROUP BY ?district

# 9.- All streets and the amount of measurements associated to each one

PREFIX ont: <http://www.group02.org/pd/ontology/PedestriansMadrid#>
SELECT ?street (COUNT(*) AS ?nMeasurements) WHERE  {
  ?measurement ont:isLocated ?measurement_point.
  ?measurement_point ont:hasStreet ?street.
  ?street rdf:type ont:Street.
} GROUP BY ?street

# 10.- First 10 measurements with their info

PREFIX ont: <http://www.group02.org/pd/ontology/PedestriansMadrid#>
SELECT ?measurement ?date ?pedestrians ?measurement_point WHERE  {
  ?measurement rdf:type ont:Measurement.
  ?measurement ont:hasDate ?date.
  ?measurement ont:hasPedestrians ?pedestrians.
  ?measurement ont:isLocated ?measurement_point.
} LIMIT 10

# 11.- Date of the latest measurement

PREFIX ont: <http://www.group02.org/pd/ontology/PedestriansMadrid#>
SELECT ?date WHERE {
  ?measurement rdf:type ont:Measurement.
  ?measurement ont:hasDate ?date.
} ORDER BY DESC(?date) LIMIT 1

# 12.- Date of the oldest measurement

PREFIX ont: <http://www.group02.org/pd/ontology/PedestriansMadrid#>
SELECT ?date WHERE {
  ?measurement rdf:type ont:Measurement.
  ?measurement ont:hasDate ?date.
} ORDER BY ASC(?date) LIMIT 1
