# -*- coding: utf-8 -*-
"""Task06.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1j4bliYb0LhZyksL7lwxnl4E8fNYYfXrU

**Task 06: Modifying RDF(s)**
"""

!pip install rdflib 
github_storage = "https://raw.githubusercontent.com/FacultadInformatica-LinkedData/Curso2021-2022/master/Assignment4/course_materials"

"""Leemos el fichero RDF de la forma que lo hemos venido haciendo"""

from rdflib import Graph, Namespace, Literal
from rdflib.namespace import RDF, RDFS
g = Graph()
g.namespace_manager.bind('ns', Namespace("http://somewhere#"), override=False)
g.namespace_manager.bind('vcard', Namespace("http://www.w3.org/2001/vcard-rdf/3.0#"), override=False)
g.parse(github_storage+"/rdf/example5.rdf", format="xml")

"""Create a new class named Researcher"""

ns = Namespace("http://somewhere#")
g.add((ns.Researcher, RDF.type, RDFS.Class))
for s, p, o in g:
  print(s,p,o)

"""**TASK 6.1: Create a new class named "University"**

"""

# --- Creation of a class named University ---
g.add((ns.University, RDF.type, RDFS.Class))
# Visualize the results
for s, p, o in g:
  print(s,p,o)

"""**TASK 6.2: Add "Researcher" as a subclass of "Person"**"""

# --- Adding 'Researcher' as subclass of 'Person' ---
g.add((ns.Researcher, RDFS.subClassOf, ns.Person))
# Visualize the results
for s, p, o in g:
  print(s,p,o)

"""**TASK 6.3: Create a new individual of Researcher named "Jane Smith"**"""

# --- Creation of 'Jane Smith' Researcher ---
# Definition of URI
janeUri = ns.JaneSmith
# Add to graph
g.add((janeUri, RDF.type, ns.Researcher))
# Visualize the results
for s, p, o in g:
  print(s,p,o)

"""**TASK 6.4: Add to the individual JaneSmith the fullName, given and family names**"""

# --- Add individuals to 'JaneSmith' resource ---
# VCard Reference & JaneUri
VCARD = Namespace("http://www.w3.org/2001/vcard-rdf/3.0#")
janeUri = ns.JaneSmith
# Definition of Literals
fullName = Literal("Jane Smith")
given = Literal("Jane")
familyNames = Literal("Smith")
# Addition
g.add((janeUri, VCARD.FN, fullName))
g.add((janeUri, VCARD.Given, given))
g.add((janeUri, VCARD.Family, familyNames))
# Visualize the results
for s, p, o in g:
  print(s,p,o)

"""**TASK 6.5: Add UPM as the university where John Smith works**"""

# --- Add UPM as John Smith University ---
# Definition of URI
upmUri = ns.UPM
johnSmith = ns.JohnSmith
# Add to graph
g.add((upmUri, RDF.type, ns.University))
# Relating UPM to John
g.add((johnSmith, ns.worksAt, upmUri))
# Visualize the results
for s, p, o in g:
  print(s,p,o)