# 1.- Get all neighborhoods in district Centro with their wikidata links
PREFIX ns: <https://data.eventsatmadrid.org/ontology#>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
PREFIX owl: <http://www.w3.org/2002/07/owl#>
SELECT DISTINCT ?NeighborhoodName ?wikidata_link
  WHERE {
    ?Neighborhood owl:sameAs ?wikidata_link .
    ?Neighborhood rdfs:label ?NeighborhoodName .
    ?Neighborhood ns:isInDistrict ?District .
    ?District rdfs:label "Centro"
  }

# 2.- Get all districts that can be found in the local data file with their wikidata links
PREFIX ns: <https://data.eventsatmadrid.org/ontology#>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
PREFIX owl: <http://www.w3.org/2002/07/owl#>
  SELECT DISTINCT ?DistrictName ?wikidata_link
  WHERE {
    ?District owl:sameAs ?wikidata_link .
    ?District rdfs:label ?DistrictName .
    ?District rdf:type ns:District 
  }
