# Query 1: Get the name and the wikidata info of each study room
PREFIX sr: <http://www.studyroomsmadrid.es/studyRoom/ontology/studyOnt>
PREFIX owl: <http://www.w3.org/2002/07/owl#>
SELECT ?name ?district ?wikiInfo
WHERE {
    ?x a sr:StudyRoom .
    ?x sr:hasName ?name .
    ?x sr:hasAddress ?y .
    ?y owl:sameAs ?wikiInfo .
}
