# -*- coding: utf-8 -*-
"""Task08.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1OmKU09Uk1Ju2uiF3T39mQ7RXOiQrXAB7

**Task 08: Completing missing data**
"""

#!pip install rdflib
github_storage = "https://raw.githubusercontent.com/FacultadInformatica-LinkedData/Curso2021-2022/master/Assignment4/course_materials"

from rdflib import Graph, Namespace, Literal, URIRef
g1 = Graph()
g2 = Graph()
g1.parse(github_storage+"/rdf/data01.rdf", format="xml")
g2.parse(github_storage+"/rdf/data02.rdf", format="xml")

"""Tarea: lista todos los elementos de la clase Person en el primer grafo (data01.rdf) y completa los campos (given name, family name y email) que puedan faltar con los datos del segundo grafo (data02.rdf). Puedes usar consultas SPARQL o iterar el grafo, o ambas cosas."""

from rdflib.namespace import RDF, RDFS

VCARD = Namespace("http://www.w3.org/2001/vcard-rdf/3.0#")
ns = Namespace("http://data.org#")

for s, p, o in g1.triples((None, RDF.type, ns.Person)):
  givenName = g2.value(s, VCARD.Given, None)
  if givenName:
    g1.add((s, VCARD.Given, givenName))

  familyName = g2.value(s, VCARD.Family, None)
  if familyName:
    g1.add((s, VCARD.Family, familyName))

  email = g2.value(s, VCARD.EMAIL, None)
  if email:
    g1.add((s, VCARD.EMAIL, email))

print(g1.serialize(format="ttl"))
